# -*- coding: utf-8 -*-
"""Anonimisasi ML

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yr5U5fd71Ndz46EcVKS5fEl0B_Gs9vXW

##Anonimisasi

#Demographic Daraset
"""

# =========================================================
# Anonimisasi data demografis
# Tujuan akademis:
# - Menghilangkan identitas langsung (direct identifiers).
# - Mengurangi granularitas quasi-identifiers (QI).
# - Menambahkan variasi terkontrol pada atribut sensitif untuk
#   memperkecil risiko re-identifikasi dan serangan inferensi.
# =========================================================

import re
import pandas as pd
import random
from hashlib import blake2b

# ================================
# 1. Baca dataset hasil serialisasi
# ================================
df = pd.read_csv("/content/Demographics_serialized.csv")
print("Kolom di dataset:", df.columns.tolist())

# otomatis gunakan kolom pertama agar tidak error
text_column = df.columns[0]

# ================================================
# 2. Fungsi hash pendek untuk pseudonymization
# ================================================
def pseudo_token(value, prefix):
    h = blake2b(value.encode(), digest_size=2).hexdigest().upper()
    return f"{prefix}_{h}"

# ==================================================
# 3. Fungsi helper untuk generalization umur & tanggal
# ==================================================
def generalize_age(text):
    match = re.search(r'(\d{1,3})\s*tahun', text)
    if match:
        age = int(match.group(1))
        if age < 20:
            r = "0–19 tahun"
        elif age < 40:
            r = "20–39 tahun"
        elif age < 60:
            r = "40–59 tahun"
        elif age < 80:
            r = "60–79 tahun"
        else:
            r = "80–99 tahun"
        text = re.sub(r'\d{1,3}\s*tahun', r, text)
    return text

def generalize_date(text):
    # format tanggal bahasa Indonesia
    text = re.sub(
        r'(\d{1,2})\s*(Januari|Februari|Maret|April|Mei|Juni|Juli|Agustus|September|Oktober|November|Desember)\s*(\d{4})',
        lambda m: f"{m.group(2)} {m.group(3)}",
        text,
        flags=re.IGNORECASE
    )

    # format YYYY-MM-DD
    text = re.sub(
        r'(\d{4})-(\d{2})-(\d{2})',
        lambda m: f"Bulan {m.group(2)} Tahun {m.group(1)}",
        text
    )

    # format DD/MM/YYYY
    text = re.sub(
        r'(\d{1,2})/(\d{1,2})/(\d{4})',
        lambda m: f"Bulan {m.group(2)} Tahun {m.group(3)}",
        text
    )

    return text

def generalize_time(text):
    return re.sub(
        r'(pukul|jam)\s*\d{1,2}[:.]\d{2}',
        'pukul sekitar jam tersebut',
        text,
        flags=re.IGNORECASE
    )

# ==============================================
# 4. Fungsi perturbation (L-diversity)
# ==============================================
def perturb_sensitive(text):
    variants = {
        "meninggal dunia": random.choice(["deceased", "passed away"]),
        "hipertensi": random.choice(["tekanan darah tinggi", "hipertensi ringan"]),
        "diabetes": random.choice(["diabetes mellitus", "kadar gula tinggi"]),
        "demensia": random.choice(["demensia ringan", "gangguan kognitif"]),
    }
    for k, v in variants.items():
        text = re.sub(k, v, text, flags=re.IGNORECASE)
    return text

# ==============================
# 5. Fungsi utama: Anonimisasi
# ==============================
def anonymize_text(text):
    if pd.isna(text):
        return text

    # ---- Direct Identifier (pseudonymization) ----
    text = re.sub(
        r'(ID\s*Pasien\s*\d+|Pasien\s*ID\s*\d+|ID\s*\d+)',
        lambda m: pseudo_token(re.search(r'\d+', m.group(0)).group(0), "Patient"),
        text,
        flags=re.IGNORECASE
    )

    # nama rumah sakit
    text = re.sub(
        r'(rumah\s*sakit\s+[A-Za-z0-9\-\s]+)',
        lambda m: pseudo_token(m.group(0).strip(), "Hospital"),
        text,
        flags=re.IGNORECASE
    )

    # ---- Quasi-Identifier ----
    text = generalize_age(text)
    text = generalize_date(text)
    text = generalize_time(text)

    text = re.sub(
        r'ras\s+[a-z\s]+',
        'ras tidak disebutkan',
        text,
        flags=re.IGNORECASE
    )

    # ---- Sensitive Attribute ----
    text = perturb_sensitive(text)

    return text

# ===========================
# 6. Terapkan anonimisasi
# ===========================
df["text_anonymized"] = df[text_column].apply(anonymize_text)
df["text_anonymized"] = df["text_anonymized"].replace({r'\n': ' '}, regex=True)

# ===========================
# 7. Simpan CSV hasil anonim
# ===========================
out_path = "/content/demographics_anoon.csv"
df[["text_anonymized"]].to_csv(
    out_path,
    index=False,
    encoding="utf-8-sig",
    quoting=1,
    sep=","
)

print("Hasil anonimisasi disimpan di:", out_path)
print("\nContoh hasil:")
print(df["text_anonymized"].head(3))

"""#Clinical Dataset

##Anonimisasi
"""

# =========================================================
# Anonimisasi teks rekam medis
# Sumber  : ClinicalData_serialisasi.csv
# Output  : ClinicalData_anonymized.csv
# =========================================================

import re
import pandas as pd
import random
from hashlib import blake2b
import csv

# === 1. Baca dataset dengan mode aman ===
csv_path = "/content/Demographics_serialized.csv"

try:
    df = pd.read_csv(csv_path, on_bad_lines='skip', engine='python')
except Exception:
    df = pd.read_csv(csv_path, sep=';', on_bad_lines='skip', engine='python')

print("Dataset berhasil dibaca!")
print("Jumlah baris:", len(df))
print("Kolom dataset:", df.columns.tolist())

# === 2. Gunakan kolom pertama (AMAN) ===
text_column = df.columns[0]

# === 3. Pseudonymization ===
def pseudo_token(value, prefix):
    h = blake2b(value.encode(), digest_size=2).hexdigest().upper()
    return f"{prefix}_{h}"

# === 4. Generalisasi ===
def generalize_age(text):
    match = re.search(r'(berusia|umur)\s*(\d{1,3})\s*tahun', text)
    if match:
        age = int(match.group(2))
        if age < 20:
            r = "0–19 tahun"
        elif age < 40:
            r = "20–39 tahun"
        elif age < 60:
            r = "40–59 tahun"
        elif age < 80:
            r = "60–79 tahun"
        else:
            r = "80–99 tahun"
        text = re.sub(r'(berusia|umur)\s*\d{1,3}\s*tahun', f"berusia {r}", text)
    return text

def generalize_number(text):
    text = re.sub(r'\d+\.\d+\s*(cm|kg|mL|menit)', r"<angka_tersembunyi> \1", text)
    text = re.sub(r'\d+\s*(cm|kg|mL|menit)', r"<angka_tersembunyi> \1", text)
    text = re.sub(r'\d+\.\d+', "<angka_tersembunyi>", text)
    return text

def generalize_time(text):
    return re.sub(r'(durasi|lama)\s+[a-z\s]*\s*\d+\s*menit', r'\1 disamarkan', text, flags=re.IGNORECASE)

# === 5. L-diversity perturbation ===
def perturb_sensitive(text):
    variants = {
        "hipertensi": random.choice(["tekanan darah tinggi", "hipertensi ringan"]),
        "diabetes mellitus": random.choice(["kadar gula tinggi", "diabetes ringan"]),
        "kanker rektal": random.choice(["kanker saluran pencernaan bawah", "tumor rektum"]),
        "kanker lambung": random.choice(["kanker saluran pencernaan atas", "tumor lambung"]),
        "batu empedu": random.choice(["kelainan empedu", "gangguan kantung empedu"]),
        "meninggal": random.choice(["tidak selamat", "deceased"]),
        "tidak meninggal": "selamat dan pulih",
    }
    for k, v in variants.items():
        text = re.sub(k, v, text, flags=re.IGNORECASE)
    return text

# === 6. Fungsi utama ===
def anonymize_text(text):
    if pd.isna(text):
        return text

    text = re.sub(r'\s+', ' ', text.strip())

    text = re.sub(
        r'(?i)nomor identifikasi\s*(\d+)',
        lambda m: pseudo_token(m.group(1), "Patient"),
        text
    )

    text = generalize_age(text)
    text = generalize_number(text)
    text = generalize_time(text)
    text = perturb_sensitive(text)

    return text

# === 7. Terapkan anonimisasi ===
df["text_anonymized"] = df[text_column].apply(anonymize_text)
df["text_anonymized"] = df["text_anonymized"].replace({r'\n': ' '}, regex=True)

# === 8. Simpan hasil ===
out_path = "/content/ClinicalData_anonymized.csv"
df[["text_anonymized"]].to_csv(
    out_path,
    index=False,
    encoding="utf-8-sig",
    quoting=csv.QUOTE_MINIMAL
)

print("\nHasil anonimisasi disimpan di:", out_path)
print("\nContoh hasil:\n")
print(df["text_anonymized"].head(5))