# -*- coding: utf-8 -*-
"""Weak Labbeling QI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KzBQpMdlO3y0mxwvV85DgMH35uHd3hG-

#Labelling QI

##Demographic Dataset
"""

# =========================================================
# Weak Labeling QI
# Tujuan:
# - Mengestimasi risiko informasi menggunakan pola QI.
# - Memberi label HIGH_RISK / LOW_RISK berdasarkan frekuensi QI.
# =========================================================

import re, numpy as np, pandas as pd, matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

plt.rcParams["figure.figsize"] = (4.8, 4.0)
RANDOM_STATE = 42

PATH_IN  = "/content/demographics_preprocessed.csv"
PATH_OUT = "/content/demographics_with_qi_labels.csv"


# =========================================================
# LOAD DATASET & CEK SINGKAT
# =========================================================
df = pd.read_csv(PATH_IN)

# 🧩 Tambahkan di sini:
if df["clean_text"].iloc[0].strip().lower() in ["text anonymized", "clean_text"]:
    print("⚠️ Header ganda terdeteksi — baris pertama dihapus otomatis.")
    df = df.drop(0).reset_index(drop=True)

assert "clean_text" in df.columns, "Kolom 'clean_text' tidak ditemukan."
df["clean_text"] = df["clean_text"].fillna("").astype(str)

print("Jumlah baris:", len(df))
print("Kolom:", df.columns.tolist())
display(df.head(10))

# Pola QI utama
# =========================================================
# QI WEAK LABELING — SINGLE LABEL (BINARY)
# =========================================================
def _norm(s: str) -> str:
    return re.sub(r"\s+", " ", s.lower()).strip()

QI_PATTERNS = {
    "age": r"(?:ber)?usia\s+\d{1,2}(?:\s*-\s*\d{1,2})?(?:\s*tahun)?|\b\d{1,2}\s*tahun\b",
    "gender": r"\b(laki[-\s]?laki|perempuan|pria|wanita|lk\b|pr\b)\b",
    "weekday": r"\b(senin|selasa|rabu|kamis|jum(?:'|)at|sabtu|minggu|mon|tue|wed|thu|fri|sat|sun)\b",
    "month": r"\b(jan(?:uari)?|feb(?:ruari)?|mar(?:et)?|apr(?:il)?|mei|jun(?:i)?|jul(?:i)?|agu(?:stus)?|sep(?:tember)?|okt(?:ober)?|nov(?:ember)?|des(?:ember)?)\b",
    "time": r"\b(jam|pukul|pkl)\b",
    "hospital": r"\b(rumah\s+sakit|rs(ud|up|ab)?\b|hospital|klinik)\b",
    "outcome": r"\b(meninggal(\s+dunia)?|wafat|deceased|passed\s+away|almarhum(?:ah)?)\b",
    "loc": r"\b(kota|kabupaten|provinsi|kec(?:amatan)?|kel(?:urahan)?)\b",
}
QI_COMPILED = {k: re.compile(v, re.IGNORECASE) for k, v in QI_PATTERNS.items()}

def qi_score(text: str) -> int:
    t = _norm(text)
    return sum(1 for rx in QI_COMPILED.values() if rx.search(t))

df["qi_score"] = df["clean_text"].apply(qi_score)

# pilih threshold 3..9 yang mendekati 50/50 agar training seimbang
candidates = range(3, 10)
n = len(df)
best_th = min(candidates, key=lambda th: abs(((df["qi_score"] >= th).sum()/n) - 0.5))

df["label"] = np.where(df["qi_score"] >= best_th, "HIGH_RISK", "LOW_RISK")

print(f"Threshold terpilih: {best_th}")
print("Distribusi label:\n", df["label"].value_counts())

df.to_csv(PATH_OUT, index=False)
print("✅ Disimpan:", PATH_OUT)

# =========================================================
# AUDIT MINI — CEK DEKAT THRESHOLD
# =========================================================
t = int(best_th)
edge = df[(df["qi_score"] >= t-1) & (df["qi_score"] <= t+1)][["clean_text","qi_score","label"]].head(30)

def _short(s, n=220):
    s = str(s)
    return s if len(s) <= n else s[:n] + " ..."
edge_view = edge.copy()
edge_view["clean_text"] = edge_view["clean_text"].apply(_short)
display(edge_view)

"""#Labelling QI

##Clinical Dataset
"""

# =========================================================
# Weak labeling berbasis QI
# Sumber  : ClinicalData_preprocessed.csv
# Output  : ClinicalData_with_qi_labels.csv (qi_score, label)
# =========================================================

"""##Import Konfig"""

# =========================================================
# CLINICAL — IMPORT & KONFIGURASI
# =========================================================
import re, numpy as np, pandas as pd, matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

plt.rcParams["figure.figsize"] = (4.8, 4.0)
RANDOM_STATE = 42

PATH_IN  = "/content/ClinicalData_preprocessed.csv"
PATH_OUT = "/content/ClinicalData_with_qi_labels.csv"

# =========================================================
# 1. LOAD DATA PREPROSES
# =========================================================
df = pd.read_csv(PATH_IN)
print(" Data preprocessed dimuat.")
print("Jumlah baris:", len(df))
print(df.head(3))

# Jika kolom baru muncul
if "text_anonymized" in df.columns and "clean_text" not in df.columns:
    df = df.rename(columns={"text_anonymized": "clean_text"})

assert "clean_text" in df.columns, "Kolom 'clean_text' tidak ditemukan!"

# =========================================================
# 2. DEFINISI POLA QI UNTUK CLINICAL
# =========================================================
QI_PATTERNS = {
    "age": r"\b(\d{1,2})\s*tahun\b|\b(0–19 tahun|20–39 tahun|40–59 tahun|60–79 tahun|80–99 tahun)\b",
    "time": r"\b(jam|pukul|menit)\b",
    "procedure": r"\b(operasi|pembedahan|tindakan|prosedur)\b",
    "location": r"\b(ruang rawat inap|igd|icu|poli|bangsal)\b",
    "outcome": r"\b(meninggal|deceased|tidak selamat|selamat|pulih)\b",
}

QI_COMPILED = {k: re.compile(v, flags=re.IGNORECASE) for k, v in QI_PATTERNS.items()}

def count_qi(text):
    """Menghitung jumlah kategori QI yang muncul dalam teks klinis."""
    t = str(text).lower()
    score = 0
    for name, rx in QI_COMPILED.items():
        if rx.search(t):
            score += 1
    return score

df["qi_score"] = df["clean_text"].apply(count_qi)

print("\nRingkasan qi_score:")
print(df["qi_score"].describe())
print("\nDistribusi qi_score:")
print(df["qi_score"].value_counts().sort_index())

# =========================================================
# 3. PENENTUAN THRESHOLD OTOMATIS (HIGH / LOW RISK)
# =========================================================
candidates = range(1, 8)
n = len(df)

def balance_metric(th):
    high = (df["qi_score"] >= th).sum()
    prop = high / n
    return abs(prop - 0.5)

best_th = min(candidates, key=balance_metric)

df["label"] = np.where(df["qi_score"] >= best_th, "HIGH_RISK", "LOW_RISK")

print(f"Threshold terpilih: {best_th}")
print("Distribusi label:\n", df["label"].value_counts())

df.to_csv(PATH_OUT, index=False)
print("Disimpan:", PATH_OUT)

# =========================================================
# 4. AUDIT MINI — CEK DATA DI SEKITAR THRESHOLD
# =========================================================
t = int(best_th)
edge = df[(df["qi_score"] >= t-1) & (df["qi_score"] <= t+1)][["clean_text","qi_score","label"]].head(30)

def _short(s, n=220):
    s = str(s)
    return s if len(s) <= n else s[:n] + " ..."

edge_view = edge.copy()
edge_view["clean_text"] = edge_view["clean_text"].apply(_short)
display(edge_view)

# =========================================================
# AUDIT MINI — CEK DEKAT THRESHOLD
# =========================================================
t = int(best_th)
edge = df[(df["qi_score"] >= t-1) & (df["qi_score"] <= t+1)][["clean_text","qi_score","label"]].head(30)

def _short(s, n=220):
    s = str(s)
    return s if len(s) <= n else s[:n] + " ..."
edge_view = edge.copy()
edge_view["clean_text"] = edge_view["clean_text"].apply(_short)
display(edge_view)