# -*- coding: utf-8 -*-
"""Feature Selection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CIk7VsOZbEj_SRplqDt6r64Xyi3CHiMi

#Feature Selection

##Demographic Dataset

###BoW
"""

# =========================================================
# Seleksi fitur menggunakan Chi-Square (BoW)
# Tujuan:
# - Memilih fitur paling relevan terhadap label klasifikasi.
# - Mengurangi dimensi untuk meningkatkan efisiensi model.
# =========================================================

import numpy as np
import pandas as pd
from sklearn.feature_selection import SelectKBest, chi2

bow_df = pd.read_csv("/content/BOW_demographics.csv")
label_df = pd.read_csv("/content/demographics_with_qi_labels.csv")

X = bow_df.values
y = label_df["label"].astype(str).values

k = min(1000, X.shape[1])   # Maksimal 1000 fitur teratas
selector = SelectKBest(score_func=chi2, k=k)
X_selected = selector.fit_transform(X, y)

selected_cols = bow_df.columns[selector.get_support()]

pd.DataFrame(X_selected, columns=selected_cols).to_csv(
    "/content/FS_BOW_demographics.csv", index=False
)

print("Feature Selection BoW selesai.")
pd.DataFrame(selected_cols[:20], columns=["Top Features"])

"""###TF-IDF"""

# =========================================================
# Seleksi fitur Chi-Square untuk TF-IDF
# Tujuan:
# - Mengambil fitur TF-IDF yang memiliki korelasi signifikan
#   dengan label HIGH/LOW RISK.
# =========================================================

tfidf_df = pd.read_csv("/content/TFIDF_demographics.csv")
label_df = pd.read_csv("/content/demographics_with_qi_labels.csv")

X = tfidf_df.values
y = label_df["label"].astype(str).values

k = min(1000, X.shape[1])
selector = SelectKBest(score_func=chi2, k=k)
X_selected = selector.fit_transform(X, y)

selected_cols = tfidf_df.columns[selector.get_support()]

pd.DataFrame(X_selected, columns=selected_cols).to_csv(
    "/content/FS_TFIDF_demographics.csv", index=False
)

print("Feature Selection TF-IDF selesai.")

"""###N-Gram"""

# =========================================================
# Seleksi fitur Bigram (Chi-Square)
# Tujuan:
# - Mengambil bigram yang berkontribusi signifikan terhadap klasifikasi.
# =========================================================

bigram_df = pd.read_csv("/content/BIGRAM_demographics.csv")
label_df = pd.read_csv("/content/demographics_with_qi_labels.csv")

X = bigram_df.values
y = label_df["label"].astype(str).values

k = min(1000, X.shape[1])
selector = SelectKBest(score_func=chi2, k=k)
X_selected = selector.fit_transform(X, y)

selected_cols = bigram_df.columns[selector.get_support()]

pd.DataFrame(X_selected, columns=selected_cols).to_csv(
    "/content/FS_BIGRAM_demographics.csv", index=False
)

print("Feature Selection Bigram selesai.")

"""#Feature Selection

##Clinical Dataset

###BoW
"""

# =========================================================
# 🎯 FEATURE SELECTION — CHI-SQUARE (BoW)
# =========================================================
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectKBest, chi2

# === Load dataset & label ===
df_bow = pd.read_csv("/content/BOW_ClinicalData_cleaned.csv")
df_label = pd.read_csv("/content/ClinicalData_with_qi_labels.csv")

X = df_bow.values
y = df_label["label"].astype(str).values

# === Chi-Square Selection ===
k = min(1000, X.shape[1])
selector = SelectKBest(chi2, k=k)
X_selected = selector.fit_transform(X, y)
mask = selector.get_support()
selected_feats = np.array(df_bow.columns)[mask]

# === Simpan hasil ===
OUT_PATH = "/content/FS_BoW_ClinicalData.csv"
pd.DataFrame(X_selected, columns=selected_feats).to_csv(OUT_PATH, index=False, encoding="utf-8-sig")

print(f"✅ Feature Selection (BoW) selesai! → {OUT_PATH}")
print(f"Sebelum: {df_bow.shape} | Sesudah: {X_selected.shape}")
print("🔝 20 fitur teratas:\n", selected_feats[:20])

"""###TF-IDF"""

# =========================================================
# 🎯 FEATURE SELECTION — CHI-SQUARE (TF-IDF)
# =========================================================
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectKBest, chi2

# === Load dataset & label ===
df_tfidf = pd.read_csv("/content/TFIDF_ClinicalData.csv")
df_label = pd.read_csv("/content/ClinicalData_with_qi_labels.csv")

X = df_tfidf.values
y = df_label["label"].astype(str).values

# === Chi-Square Selection ===
k = min(1000, X.shape[1])
selector = SelectKBest(chi2, k=k)
X_selected = selector.fit_transform(X, y)
mask = selector.get_support()
selected_feats = np.array(df_tfidf.columns)[mask]

# === Simpan hasil ===
OUT_PATH = "/content/FS_TFIDF_ClinicalData.csv"
pd.DataFrame(X_selected, columns=selected_feats).to_csv(OUT_PATH, index=False, encoding="utf-8-sig")

print(f"✅ Feature Selection (TF-IDF) selesai! → {OUT_PATH}")
print(f"Sebelum: {df_tfidf.shape} | Sesudah: {X_selected.shape}")
print("🔝 20 fitur teratas:\n", selected_feats[:20])

"""###N-Gram"""

# =========================================================
# 🎯 FEATURE SELECTION — CHI-SQUARE (BIGRAM)
# =========================================================
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectKBest, chi2

# === Load dataset & label ===
df_bigram = pd.read_csv("/content/NGRAM_ClinicalData_cleaned.csv")
df_label = pd.read_csv("/content/ClinicalData_with_qi_labels.csv")

X = df_bigram.values
y = df_label["label"].astype(str).values

# === Chi-Square Selection ===
k = min(1000, X.shape[1])
selector = SelectKBest(chi2, k=k)
X_selected = selector.fit_transform(X, y)
mask = selector.get_support()
selected_feats = np.array(df_bigram.columns)[mask]

# === Simpan hasil ===
OUT_PATH = "/content/FS_BIGRAM_ClinicalData.csv"
pd.DataFrame(X_selected, columns=selected_feats).to_csv(OUT_PATH, index=False, encoding="utf-8-sig")

print(f"✅ Feature Selection (Bigram) selesai! → {OUT_PATH}")
print(f"Sebelum: {df_bigram.shape} | Sesudah: {X_selected.shape}")
print("🔝 20 fitur teratas:\n", selected_feats[:20])