# -*- coding: utf-8 -*-
"""Uji Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vyy-x3mbNEzTvw3NP0tJQC_CNOBgazE_

#UJI MODEL

##Demographic Dataset
"""

# =========================================================
# 🧪 UJI MODEL — DEMOGRAPHIC DATA (Versi Lengkap & FINAL)
# =========================================================
# ✅ Aman dari error "could not convert string to float"
# ✅ Menyimpan hasil prediksi lengkap (true_label, predicted_label, text)
# ✅ Siap digunakan untuk analisis error
# =========================================================

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
import numpy as np
import os

# === 1️⃣ Load dataset utama (dengan teks & label) ===
df = pd.read_csv("/content/demographics_with_qi_labels.csv")
X_text = df["clean_text"].astype(str)
y = df["label"].astype(str)

# === 2️⃣ Path hasil Feature Selection ===
SET_FEATURES = {
    "BoW_FS": "/content/FS_BOW_demographics.csv",
    "TFIDF_FS": "/content/FS_TFIDF_demographics.csv",
    "BIGRAM_FS": "/content/FS_BIGRAM_demographics.csv",
}

# === 3️⃣ Model yang diuji ===
models = {
    "Logistic Regression": LogisticRegression(max_iter=2000, solver="liblinear"),
    "Naive Bayes": MultinomialNB(),
}

# === 4️⃣ Loop semua kombinasi fitur & model ===
for feat_name, feat_path in SET_FEATURES.items():
    print(f"\n{'#'*100}")
    print(f"📂 Memuat fitur: {feat_name} dari {feat_path}")

    try:
        # === Load file fitur hasil seleksi ===
        X_df = pd.read_csv(feat_path)

        # Bersihkan kolom non-numerik / indeks
        if X_df.columns[0].lower() in ['unnamed: 0', '0', 'index']:
            print(f"⚠️ Menghapus kolom indeks: {X_df.columns[0]}")
            X_df = X_df.drop(columns=[X_df.columns[0]])

        non_numeric_cols = X_df.select_dtypes(exclude=['number']).columns.tolist()
        if non_numeric_cols:
            print(f"⚠️ Menghapus kolom non-numerik: {non_numeric_cols}")
            X_df = X_df.drop(columns=non_numeric_cols)

        # Jika belum numerik, paksa konversi
        if X_df.select_dtypes(include=['number']).empty:
            print("⚠️ Tidak ada kolom numerik — mencoba konversi manual...")
            X_df = X_df.apply(pd.to_numeric, errors='coerce')
            X_df = X_df.dropna(axis=1, how='all')

        if X_df.shape[1] == 0:
            print(f"⛔ File {feat_path} tidak memiliki fitur valid. Dilewati.")
            continue

        X = X_df.values

        # === Split data ===
        X_train, X_test, y_train, y_test, text_train, text_test = train_test_split(
            X, y, X_text, test_size=0.2, random_state=42, stratify=y
        )

        # === Jalankan semua model ===
        for model_name, model in models.items():
            print(f"\n{'='*100}")
            print(f"🔹 MODEL: {model_name} | FITUR: {feat_name}")
            print(f"{'='*100}")

            # Latih model
            model.fit(X_train, y_train)
            y_pred = model.predict(X_test)

            # === Classification Report ===
            print("\n📋 Classification Report:")
            print(classification_report(y_test, y_pred, digits=4))

            # === Confusion Matrix ===
            cm = confusion_matrix(y_test, y_pred)
            plt.figure(figsize=(4,4))
            sns.heatmap(
                cm, annot=True, fmt="d", cmap="Blues",
                xticklabels=sorted(df['label'].unique()),
                yticklabels=sorted(df['label'].unique())
            )
            plt.title(f"Confusion Matrix — {model_name} ({feat_name})")
            plt.xlabel("Predicted Label")
            plt.ylabel("True Label")
            plt.tight_layout()
            plt.show()

            # === Simpan hasil prediksi (dengan teks) ===
            df_pred = pd.DataFrame({
                "text": text_test.values,
                "true_label": y_test.values,
                "predicted_label": y_pred
            })

            result_path = f"/content/Result_{model_name.replace(' ','_')}_{feat_name}_Demographic.csv"
            error_path  = f"/content/Error_{model_name.replace(' ','_')}_{feat_name}_Demographic.csv"

            df_pred.to_csv(result_path, index=False, encoding="utf-8-sig")

            # Simpan hanya error
            df_err = df_pred[df_pred["true_label"] != df_pred["predicted_label"]]
            df_err.to_csv(error_path, index=False, encoding="utf-8-sig")

            print(f"📁 Hasil prediksi disimpan di: {result_path}")
            print(f"❌ Jumlah prediksi salah: {len(df_err)} (disimpan di {error_path})")

            # Tampilkan contoh error (jika ada)
            if not df_err.empty:
                print("\n🔍 Contoh kesalahan prediksi:")
                display(df_err.head(5))
            else:
                print("✅ Tidak ada prediksi yang salah pada dataset uji.")

    except Exception as e:
        print(f"🚨 Error saat memproses {feat_name}: {e}")
        continue

"""#UJI MODEL

##Clinical Dataset
"""

# =========================================================
# 🧪 UJI MODEL — CLINICAL DATA (PAKAI FILE FEATURE SELECTION)
# =========================================================
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB

# === 1️⃣ Load dataset utama ===
df = pd.read_csv("/content/ClinicalData_with_qi_labels.csv")
y = df["label"].astype(str)
X_text = df["clean_text"].astype(str)

print(f"✅ Dataset utama dimuat: {df.shape[0]} baris")

# === 2️⃣ Load hasil feature selection ===
SET_FEATURES = {
    "BoW_FS": "/content/FS_BoW_ClinicalData.csv",
    "TFIDF_FS": "/content/FS_TFIDF_ClinicalData.csv",
    "BIGRAM_FS": "/content/FS_BIGRAM_ClinicalData.csv"
}

feature_sets = {}
for name, path in SET_FEATURES.items():
    X = pd.read_csv(path)
    feature_sets[name] = X
    print(f"• {name}: {X.shape}")

# === 3️⃣ Definisikan model yang akan diuji ===
models = {
    "Logistic Regression": LogisticRegression(max_iter=2000, solver="liblinear"),
    "Naive Bayes": MultinomialNB(),
}

# === 4️⃣ Uji kombinasi fitur–model ===
for feat_name, X in feature_sets.items():
    print(f"\n{'#'*100}")
    print(f"📂 Uji model dengan fitur: {feat_name}")

    X_train, X_test, y_train, y_test, text_train, text_test = train_test_split(
        X, y, X_text, test_size=0.2, random_state=42, stratify=y
    )

    for model_name, model in models.items():
        print(f"\n{'='*100}")
        print(f"🔹 MODEL: {model_name} | FITUR: {feat_name}")
        print(f"{'='*100}")

        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        # === Classification Report ===
        print("\n📋 Classification Report:")
        print(classification_report(y_test, y_pred, digits=4))

        # === Confusion Matrix ===
        cm = confusion_matrix(y_test, y_pred)
        plt.figure(figsize=(4,4))
        sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
                    xticklabels=sorted(y.unique()), yticklabels=sorted(y.unique()))
        plt.title(f"Confusion Matrix — {model_name} ({feat_name})")
        plt.xlabel("Predicted Label")
        plt.ylabel("True Label")
        plt.tight_layout()
        plt.show()

        # === Simpan hasil prediksi ===
        df_pred = pd.DataFrame({
            "text": text_test.values,
            "true_label": y_test.values,
            "predicted_label": y_pred
        })

        result_path = f"/content/Result_{model_name.replace(' ','_')}_{feat_name}_Clinical.csv"
        df_pred.to_csv(result_path, index=False, encoding="utf-8-sig")

        print(f"📁 Disimpan ke: {result_path}")