# -*- coding: utf-8 -*-
"""Analisis Error

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10sTZnzhg6EE7ySTqkchYtoSHNugZf2YD

#Error Analisis

##Demographic Dataset
"""

# =========================================================
# NAALISIS ERROR — SEMUA PENDEKATAN FITUR (BoW, TF-IDF, Bigram)
# =========================================================
# 1️ Loop otomatis semua kombinasi model + fitur
# 2️ Tampilkan jumlah error, contoh kesalahan, dan kata dominan
# 3️ Visualisasi distribusi kesalahan
# 4️ Simpan ringkasan lengkap ke CSV
# =========================================================

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from collections import Counter
import os

# === Semua kombinasi hasil prediksi ===
RESULT_FILES = {
    "BoW_FS": {
        "Logistic Regression": "/content/Result_Logistic_Regression_BoW_FS_Demographic.csv",
        "Naive Bayes": "/content/Result_Naive_Bayes_BoW_FS_Demographic.csv",
    },
    "TFIDF_FS": {
        "Logistic Regression": "/content/Result_Logistic_Regression_TFIDF_FS_Demographic.csv",
        "Naive Bayes": "/content/Result_Naive_Bayes_TFIDF_FS_Demographic.csv",
    },
    "BIGRAM_FS": {
        "Logistic Regression": "/content/Result_Logistic_Regression_BIGRAM_FS_Demographic.csv",
        "Naive Bayes": "/content/Result_Naive_Bayes_BIGRAM_FS_Demographic.csv",
    }
}

# ===  Fungsi bantu ===
def common_words(df, col="text", topn=15):
    if col not in df.columns:
        return pd.DataFrame(columns=["Kata", "Frekuensi"])
    all_text = " ".join(df[col].astype(str).tolist()).lower().split()
    common = Counter(all_text).most_common(topn)
    return pd.DataFrame(common, columns=["Kata", "Frekuensi"])

def plot_error_distribution(df, model_name, feat_name):
    plt.figure(figsize=(4,3))
    sns.countplot(x="true_label", data=df, hue="true_label", palette="Blues", legend=False)
    plt.title(f"Distribusi Kesalahan — {model_name} ({feat_name})")
    plt.xlabel("True Label")
    plt.ylabel("Jumlah Salah Prediksi")
    plt.tight_layout()
    plt.show()

# === Analisis semua kombinasi ===
summary_rows = []

print("#" * 100)
print("📊 Jumlah kesalahan prediksi untuk semua model & fitur:\n")

for feat_name, models in RESULT_FILES.items():
    print(f"Analisis fitur: {feat_name}")
    for model_name, path in models.items():
        if not os.path.exists(path):
            print(f"   File tidak ditemukan: {path}")
            continue

        res = pd.read_csv(path)
        res["is_correct"] = res["true_label"] == res["predicted_label"]
        err_df = res[~res["is_correct"]]

        total = len(res)
        errors = len(err_df)
        err_percent = errors / total * 100

        print(f"   • {model_name:<20}: {errors} dari {total} data ({err_percent:.2f}%)")

        summary_rows.append({
            "Fitur": feat_name,
            "Model": model_name,
            "Total Data Uji": total,
            "Jumlah Error": errors,
            "Persentase Error (%)": round(err_percent, 2)
        })
    print("-" * 100)

# === Contoh kesalahan & kata dominan ===
for feat_name, models in RESULT_FILES.items():
    for model_name, path in models.items():
        if not os.path.exists(path):
            continue

        print(f"\n{'='*100}")
        print(f"Contoh kesalahan prediksi — {model_name} ({feat_name})")
        print(f"{'='*100}")

        res = pd.read_csv(path)
        res["is_correct"] = res["true_label"] == res["predicted_label"]
        err_df = res[~res["is_correct"]]

        # Contoh kesalahan
        if "text" in err_df.columns:
            display(err_df.head(10)[["text", "true_label", "predicted_label", "is_correct"]])
        else:
            print("Kolom 'text' tidak ditemukan. Menampilkan label saja.\n")
            display(err_df.head(10)[["true_label", "predicted_label", "is_correct"]])

        # Kata paling sering
        print(f"\n Kata paling sering muncul dalam prediksi salah — {model_name} ({feat_name}):")
        display(common_words(err_df, col="text", topn=15))

        # Distribusi kesalahan
        if not err_df.empty:
            plot_error_distribution(err_df, model_name, feat_name)

# === Simpan ringkasan akhir ===
summary = pd.DataFrame(summary_rows)
summary_path = "/content/Error_Analysis_Summary_AllFeatures.csv"
summary.to_csv(summary_path, index=False, encoding="utf-8-sig")

print(f"\n Ringkasan analisis error disimpan di: {summary_path}")
display(summary)

"""#Error Analisis

##Clinical Dataset
"""

# =========================================================
# 🧠 ANALISIS ERROR — CLINICAL DATA
# =========================================================
# Analisis semua hasil uji model (BoW, TF-IDF, Bigram)
# dari Logistic Regression & Naive Bayes
# =========================================================

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from collections import Counter
import os

# === 1️⃣ Daftar file hasil uji model ===
RESULT_FILES = {
    "Logistic Regression": [
        "/content/Result_Logistic_Regression_BoW_FS_Clinical.csv",
        "/content/Result_Logistic_Regression_TFIDF_FS_Clinical.csv",
        "/content/Result_Logistic_Regression_BIGRAM_FS_Clinical.csv"
    ],
    "Naive Bayes": [
        "/content/Result_Naive_Bayes_BoW_FS_Clinical.csv",
        "/content/Result_Naive_Bayes_TFIDF_FS_Clinical.csv",
        "/content/Result_Naive_Bayes_BIGRAM_FS_Clinical.csv"
    ]
}

# === 2️⃣ Fungsi bantu ===
def common_words(df, col="text", topn=15):
    """Hitung kata paling sering muncul di teks salah prediksi"""
    if col not in df.columns:
        return pd.DataFrame(columns=["Kata", "Frekuensi"])
    all_text = " ".join(df[col].astype(str).tolist()).lower().split()
    common = Counter(all_text).most_common(topn)
    return pd.DataFrame(common, columns=["Kata", "Frekuensi"])

def plot_error_distribution(df, model_name, feat_name):
    """Plot distribusi kesalahan antar label"""
    plt.figure(figsize=(4,3))
    sns.countplot(x="true_label", data=df, hue="true_label", palette="Blues", legend=False)
    plt.title(f"Distribusi Kesalahan — {model_name} ({feat_name})")
    plt.xlabel("True Label")
    plt.ylabel("Jumlah Salah Prediksi")
    plt.tight_layout()
    plt.show()

# === 3️⃣ Loop semua hasil model ===
summary_rows = []

print("#" * 100)
print("📊 Jumlah kesalahan prediksi:")

for model_name, file_list in RESULT_FILES.items():
    for path in file_list:
        if not os.path.exists(path):
            print(f"⚠️ File tidak ditemukan: {path}")
            continue

        # Ambil nama fitur dari path
        feat_name = os.path.basename(path).split("_")[3]  # BoW_FS / TFIDF_FS / BIGRAM_FS

        # Load hasil prediksi
        res = pd.read_csv(path)

        # Tambahkan kolom status benar/salah
        res["is_correct"] = res["true_label"] == res["predicted_label"]

        # Ambil data salah prediksi
        err_df = res[~res["is_correct"]]
        total = len(res)
        errors = len(err_df)
        err_percent = errors / total * 100

        print(f"   • {model_name:<20} ({feat_name:<8}) : {errors} dari {total} data ({err_percent:.2f}%)")

        summary_rows.append({
            "Model": model_name,
            "Fitur": feat_name,
            "Total Data Uji": total,
            "Jumlah Error": errors,
            "Persentase Error (%)": round(err_percent, 2)
        })

        # === Contoh kesalahan ===
        print(f"\n🔍 Contoh kesalahan prediksi — {model_name} ({feat_name}):")
        if "text" in err_df.columns:
            display(err_df.head(10)[["text", "true_label", "predicted_label", "is_correct"]])
        else:
            print("ℹ️ Kolom 'text' tidak ditemukan. Menampilkan label saja.\n")
            display(err_df.head(10)[["true_label", "predicted_label", "is_correct"]])

        # === Kata paling sering muncul di prediksi salah ===
        print(f"📈 Kata paling sering muncul dalam prediksi salah — {model_name} ({feat_name}):")
        common_df = common_words(err_df, col="text", topn=15)
        display(common_df)

        # === Plot distribusi kesalahan ===
        if not err_df.empty:
            plot_error_distribution(err_df, model_name, feat_name)

print("\n" + "#" * 100)

# === 4️⃣ Simpan ringkasan keseluruhan ===
summary = pd.DataFrame(summary_rows)
summary_path = "/content/Error_Analysis_Summary_Clinical.csv"
summary.to_csv(summary_path, index=False, encoding="utf-8-sig")

print(f"\n✅ Ringkasan analisis error disimpan di: {summary_path}")
display(summary)